from typing import Annotated, Optional
from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from sqlalchemy.orm import Session, object_session
from pydantic import BaseModel

from api.models import get_db, AuthorizedUser
from api.utils.security import decode_access_token
from api.config import get_settings

settings = get_settings()

oauth2_scheme = OAuth2PasswordBearer(tokenUrl=f"{settings.api.api_prefix}/auth/token")

class TokenData(BaseModel):
    username: Optional[str] = None

async def get_current_user(token: Annotated[str, Depends(oauth2_scheme)], db: Session = Depends(get_db)):
    import logging
    logger = logging.getLogger(__name__)
    
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    
    logger.info(f"Validating token: {token[:20]}...")
    
    payload = decode_access_token(token)
    if payload is None:
        logger.error("Token decode failed")
        raise credentials_exception
        
    username: str = payload.get("sub")
    if username is None:
        logger.error("No 'sub' in token payload")
        raise credentials_exception
        
    logger.info(f"Token valid for user: {username}")
    token_data = TokenData(username=username)
    
    user = db.query(AuthorizedUser).filter(AuthorizedUser.Correo_Electronico == token_data.username).first()
    if user is None:
        logger.error(f"User not found: {username}")
        raise credentials_exception
        
    if not user.Estado:
        logger.error(f"User inactive: {username}")
        raise HTTPException(status_code=400, detail="Inactive user")
    
    logger.info(f"User authenticated successfully: {username}")
    return user

async def get_current_active_user(current_user: Annotated[AuthorizedUser, Depends(get_current_user)]):
    if not current_user.Estado:
        raise HTTPException(status_code=400, detail="Inactive user")
    return current_user

class RoleChecker:
    def __init__(self, allowed_roles: list[str]):
        self.allowed_roles = allowed_roles

    def __call__(self, user: AuthorizedUser = Depends(get_current_active_user)):
        logger.info(f"RoleChecker Checking user: {user.Correo_Electronico} (ID: {user.id_autorizado})")
        logger.info(f"User Data - id_rol: {user.id_rol}, Nivel_Acceso: {user.Nivel_Acceso}")
        logger.info(f"Allowed Roles: {self.allowed_roles}")

        # 1. Check if user has a role assigned
        if not user.id_rol:
             logger.info("No id_rol found, attempting legacy Nivel_Acceso check")
             # Fallback to legacy Nivel_Acceso check if id_rol is missing (during migration)
             if user.Nivel_Acceso in self.allowed_roles:
                 logger.info("Legacy check passed")
                 return
                 
             logger.warning(f"Legacy check failed. Nivel_Acceso '{user.Nivel_Acceso}' not in allowed roles.")
             raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN, 
                detail=f"No role assigned. Required: {self.allowed_roles}"
            )

        # 2. Get Role Name from DB
        # Since models are automapped, we might need to access the relationship or query explicitly.
        # For safety/simplicity in this step, we'll query the Role table if the relationship isn't guaranteed loaded.
        # However, accessing user.role (or user.ROL) is better if available.
        # Let's try to access the relationship if automap created it, otherwise strictly query.
        
        # NOTE: accessing user.ROL assumes the relationship name generated by automap.
        # Usually it's the class name of the related table.
        # If that fails, we should handle it. But logically, we just need to verify the user's role NAME matches allowed.
        
        # We'll use the session from the user object if attached, or cleaner: check ID if we knew IDs.
        # unique_id check is hard because allowed_roles are names ('CEO', etc.)
        
        # Let's trust that the 'Nivel_Acceso' field might eventually be deprecated, 
        # but for now, we want to check the REAL role name from the ROL table.
        
        # Accessing the DB session from the user instance (Standard SQLAlchemy)
        db = object_session(user)
        if not db:
            # Should not happen in a dependency chain request
             logger.error("No database session attached to user object")
             raise HTTPException(status_code=500, detail="Database session error")

        from api.models import Role # Lazy import to avoid circulars
        
        user_role = db.query(Role).filter(Role.id_rol == user.id_rol).first()
        
        if user_role:
            logger.info(f"Found Role in DB: ID={user_role.id_rol}, Name='{user_role.NombreRol}'")
        else:
            logger.warning(f"Role ID {user.id_rol} not found in ROL table!")
        
        if not user_role or user_role.NombreRol not in self.allowed_roles:
             logger.warning(f"Role validation failed. '{user_role.NombreRol if user_role else 'None'}' not in {self.allowed_roles}")
             raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN, 
                detail=f"Operation not permitted. Required roles: {self.allowed_roles}"
            )
        
        logger.info("Role validation passed")
